#include<iostream>

using namespace std;

string decodeAtIndex(string s, int k) {
        // string word;
        // string solution;
        // word.reserve(2^64 - 1);
        // solution.reserve(2^64 - 1);
        // for(int i=0;i<s.length();i++)
        // {
        //     if(isalpha(s[i]))
        //     {
        //         solution.push_back(s[i]);
        //         continue;
        //     }
        //     if(isdigit(s[i]))
        //     {
        //         word = solution.substr(0,solution.length());
        //         int j = int(s[i])-48;
        //         for(j;j>1;j-- )
        //         {
        //             solution+=word;
        //         }
           
        //     }
        //     if(solution.length()>=k)
        //     {
        //         cout<<solution.length();
        //         break;
        //     } 
        // }
        // string l;
        // l .push_back(solution[k-1] );
        
        // return l;


        for(int)
    }

int main()
{
    string a = decodeAtIndex("y959q969u3hb22odq595",222280369);
    cout<<a<<endl;
}